patients:
  id: "Chart #"
  first_name: First Name
  last_name: Last Name
  date_of_birth: Date of Birth
  age: Age (during the clinic)
  sex: Gender
  street: Street
  city: City
  state: State
  zip: Zip
  phone: Phone
  race: Race
  travel_time: Travel Time (in days)
  chief_complaint: Chief Complaint
  last_dental_visit: Last Dental Visit
  pain: In Pain?
  pain_length_in_days: Pain Length (in days)
  previous_chart_number: Previous Chart Number (for returning patients)

procedures:
  patient_id: "Chart #"
  procedure:
    code: Procedure Code
    description: Procedure Description
    cost: Cost
  tooth_number: Tooth Number
  surface_code: Surface Code

prescriptions:
  patient_id: "Chart #"
  prescription:
    full_description: Prescription
    cost: Cost

pre_meds:
  patient_id: "Chart #"
  pre_med:
    description: Pre-Med
    cost: Cost

patient_flows:
  patient_id: "Chart #"
  treatment_area:
    name: Treatment Area
  area_humanized: Clinic Area
  created_at:
    to_time: Visited At
